In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
matrix = np.array([[2, 3, 4], [3, 5, 6], [6, 8, 2]])
matrix

array([[2, 3, 4],
       [3, 5, 6],
       [6, 8, 2]])

In [3]:
type(matrix)

numpy.ndarray

In [4]:
matrix.shape

(3, 3)

In [5]:
np.linspace(2, 20, 10)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [6]:
np.random.rand(4)

array([0.03408794, 0.77655874, 0.74271326, 0.89910089])

In [7]:
np.random.rand(2, 3)

array([[0.01525224, 0.70267696, 0.90568519],
       [0.75027259, 0.28482443, 0.70005659]])

In [8]:
np.random.randint(3)

1

In [9]:
np.random.randint(1, 50, 10)

array([41, 22, 20, 49,  6, 18, 32, 34, 39, 29])

In [10]:
np.random.randint(1, 50)

3

In [11]:
np.random.randint(0, 20, (3, 4))

array([[19, 11, 12, 19],
       [12, 17, 10,  6],
       [14,  0, 16,  0]])

In [12]:
arr = np.arange(25)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
arr.shape

(25,)

In [15]:
rarr = arr.reshape(5, 5)
rarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
arr.shape

(25,)

In [17]:
type(arr)

numpy.ndarray

In [18]:
a = arr.reshape(1,25)

In [19]:
a.shape

(1, 25)

In [20]:
a.max()

24

In [21]:
a.argmax()

24

In [22]:
np.sort(a)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [23]:
rarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
np.sort(rarr)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
new = np.array([[6, 2], [5, 3]])
new

array([[6, 2],
       [5, 3]])

In [26]:
np.sort(new, axis=0)

array([[5, 2],
       [6, 3]])

In [27]:
np.sum(new, axis=0)

array([11,  5])

In [28]:
np.sum(new, axis=1)

array([8, 8])

 # Indexing and Selection

In [29]:
arr = np.arange(0, 10)

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
slice_of_arr = arr[0:3]
slice_of_arr

array([0, 1, 2])

In [32]:
slice_of_arr[:] = 99

In [33]:
slice_of_arr

array([99, 99, 99])

In [34]:
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

# Using copy

In [35]:
another_slice = arr.copy()
another_slice

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [36]:
another_slice[:3] = 100

In [37]:
another_slice

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [38]:
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [39]:
b = np.array([[3, 5, 1], [1, 8, 4], [6, 3, 2]])
b

array([[3, 5, 1],
       [1, 8, 4],
       [6, 3, 2]])

In [40]:
b[1]

array([1, 8, 4])

In [41]:
b[:2]

array([[3, 5, 1],
       [1, 8, 4]])

In [42]:
b[:2, :2]

array([[3, 5],
       [1, 8]])

In [43]:
np.sort(b, axis=0)

array([[1, 3, 1],
       [3, 5, 2],
       [6, 8, 4]])

In [46]:
df = pd.DataFrame(data=[[1, 2, 3], [4, 5, 6]], columns=['col1', 'col2', 'col3'], index=['USA', 'CANADA'])
df

col1  col2  col3
USA        1     2     3
CANADA     4     5     6